### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function val() on int in ddn/sapp/src/PDFDoc.php:459

### ISSUE THREAD

**Issue by parallels999** [dealfonso/sapp#26]
I'm trying [pdfsigni.php](https://github.com/dealfonso/sapp/blob/main/pdfsigni.php)
And i'm getting
```
PHP Fatal error:  Uncaught Error: Call to a member function val() on int in ddn\sapp\src\PDFDoc.php:459
Stack trace:
#0 ddn\sapp\src\PDFDoc.php(690): ddn\sapp\PDFDoc->_generate_signature_in_document()
#1 ddn\sapp\src\PDFDoc.php(823): ddn\sapp\PDFDoc->to_pdf_file_b(false)
#2 ddn\sapp\pdfsigni.php(78): ddn\sapp\PDFDoc->to_pdf_file_s()
#3 {main}
  thrown in ddn\sapp\src\PDFDoc.php on line 459
```
https://github.com/dealfonso/sapp/blob/01acefd42ce5dfb4d572b76db2b1871270991abe/src/PDFDoc.php#L458-L460
`ddn\sapp\src\PDFDoc.php on line 459` is `$page_rotation->val()`

I'm doing something wrong? i did not change anything

**Btw, thanks for the amazing work**

**Comment by parallels999** [comment]
>could you please provide an example?

@dealfonso I'm trying [pdfsigni.php](https://github.com/dealfonso/sapp/blob/main/pdfsigni.php), that is the exmaple
