### ISSUE TITLE
Extracting all signatures

### ISSUE THREAD

**Issue by henrywood** [dealfonso/sapp#58]
How can I extract all signatures from a PDF (to validate them one by one) ?

Please help !

Thanks !

**Comment by dealfonso** [comment]
Do you need the signatures? Or the signed documents at each version?

Please check method `get_signatures`

**Comment by henrywood** [comment]
@dealfonso Thanks ! I don't know how I was able to overlook that method :)

**Comment by henrywood** [comment]
This line:

https://github.com/dealfonso/sapp/blob/main/src/PDFDoc.php#L1076C1-L1076C60

throws a TypeError on some signed PDFs:

PHP Warning:  Undefined array key 0 in /tmp/sapp/vendor/ddn/sapp/src/PDFDoc.php on line 1076
PHP Fatal error:  Uncaught TypeError: Unsupported operand types: array + bool in /tmp/sapp/vendor/ddn/sapp/src/PDFDoc.php:1076
Stack trace:
#0 /tmp/sapp/vendor/ddn/sapp/src/PDFDoc.php(1090): ddn\sapp\PDFDoc->get_signatures()
#1 /tmp/sapp/test_verify.php(19): ddn\sapp\PDFDoc->get_signature_count()
#2 {main}
  thrown in /tmp/sapp/vendor/ddn/sapp/src/PDFDoc.php on line 1076
  
  (I am running PHP 8.2)
  
  Apparently $cert[0] is not set such cases ?

**Comment by henrywood** [comment]
Works: [pdf_digital_signature_timestamp.pdf](https://github.com/dealfonso/sapp/files/12841164/pdf_digital_signature_timestamp.pdf)
Produces the typeError above: [sample01.pdf](https://github.com/dealfonso/sapp/files/12841165/sample01.pdf)

**Comment by erikn69** [comment]
I will try to correct it

**Comment by erikn69** [comment]
#59 avoids the TypeError
